mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from study.views import *
from mysite import settings
from django.conf.urls.static import static

# include позволяет подгружать в url из проектов

urlpatterns = [
    path('study/', include('study.urls', namespace="study")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

mysite/study/urls.py
from django.urls import path
from . import views

app_name = 'study'

urlpatterns = [
    path('', views.index, name='index'),  # http://127.0.0.1:8000/study/
    path('login/', views.login, name='login'),  # http://127.0.0.1:8000/study/login/
    path('groups/<int:group>/', views.study_progress, name='study_progress'),
    # http://127.0.0.1:8000/study/study_progress/num/
    # адрес страницы, ссылка на функцию, имя внутри программы (например, для использования в шаблонах)
    path('about/', views.about, name='about'),
    path('groups/', views.groups, name='groups'),
    path('new_obj/', views.add_objective, name='new_obj'),
    path('create_obj/', views.create_obj, name='create_obj'),
]

mysite/study/models.py
from django.db import models
from django.urls import reverse
import datetime


class Student (models.Model):
    surname = models.CharField(max_length=30, verbose_name='Фамилия')
    name = models.CharField(max_length=30, verbose_name='Имя')
    group = models.ForeignKey('Group', on_delete=models.PROTECT, verbose_name='Группа')

    def __str__(self):
        return self.surname + ' ' + self.name+'; Группа: '+str(self.group)

    class Meta: # Для отображения в админ-панели
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'
        ordering = ['group', 'surname']


class Group (models.Model):
    number = models.CharField(max_length=5, verbose_name='Номер группы')
    study_year = models.IntegerField(verbose_name='Год обучения')

    def __str__(self):
        return self.number

    def get_absolute_url(self):
        return reverse('study_progress', kwargs={'group_id': self.pk})

    class Meta:  # Для отображения в админ-панели
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Progress(models.Model):
    student = models.ForeignKey('Student', on_delete=models.PROTECT, verbose_name='Студент')
    work = models.ForeignKey('Work', on_delete=models.CASCADE, verbose_name='Задание')
    NO = 'Нет'
    REVIEW = 'Проверка'
    CORRECTION = 'Правки'
    COMPLETED = 'Сдано'
    STATUS = [(NO, 'Нет'), (REVIEW, 'Проверка'), (CORRECTION, 'Правки'), (COMPLETED, 'Сдано')]
    status = models.CharField(max_length=10, choices=STATUS, default=NO, verbose_name='Статус работы')
    comment = models.TextField(max_length=100, blank=True, null=True, verbose_name='Комментарий')

    class Meta:  # Для отображения в админ-панели
        verbose_name = 'Работа'
        verbose_name_plural = 'Работы'
        ordering = ['work']

    def __str__(self):
        return str(self.student)+'; '+str(self.work)+'; '+str(self.status)


class Work(models.Model):
    name = models.CharField(max_length=20, verbose_name='Задача')
    difficulty = models.CharField(max_length=15, verbose_name='Сложность')
    photo = models.ImageField(upload_to='photos/%m/%d', null=True, blank=True, verbose_name='Фото')
    LOW = 'LOW'
    MIDDLE = 'MIDDLE'
    HIGH = 'HIGH'
    SPECIAL = 'SPECIAL'
    DIFFICULTY = [(LOW, 'Низкая'), (MIDDLE, 'Средняя'), (HIGH, 'Высокая'), (SPECIAL, 'Очень высокая')]
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY, default=MIDDLE, verbose_name='Сложность')

    date = models.DateField(default=datetime.date.today, verbose_name='Дата задания', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:  # Для отображения в админ-панели
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'
        ordering = ['date']

mysite/study/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.template import loader
from .models import *  # Чтобы работать с данными из моделей

# Я ниибу, почему он у меня в тегах html не робит без указания пространства имен


menu = [{'title': 'Успеваемость', 'url_name': 'study:groups'},
        {'title': 'Загрузить задание', 'url_name': 'study:create_obj'},
        {'title': 'Учебные материалы', 'url_name': 'study:index'},
        {'title': 'Контакты', 'url_name': 'study:about'},
        ]


def index(request):
    context = {'title': 'Учебный сайт',
               'menu': menu}
    return render(request, 'study/index.html', context=context)


def login(request):
    return HttpResponse('<h2>Заглушка страницы авторизации<h2>')


def groups(request):
    group_list = Group.objects.all().order_by('number')
    return render(request, 'study/groups.html', {'title': 'Список групп', 'groups': group_list})


def study_progress(request, group):
    students = Student.objects.all()
    works = Work.objects.all()
    progress = Progress.objects.all()
    list_w = []
    for s in students:
        if s.group_id==group:
            table = []
            for p in progress:
                if s.pk == p.student_id:
                    for w in works:
                        if w.pk == p.work_id:
                            # table.append({'surname': s.surname, 'w_name': w.name, 'status': p.status})
                            table.append({'w_name': w.name, 'status': p.status})
            list_w.append({'surname': s.surname, 'table': table})

    return render(request, 'study/progress.html', {'title': 'Успеваемость', 'headers': works, 'progress': list_w})


def add_objective(request):
    context = {'title': 'Учебный сайт',
               'menu': menu}
    name =""
    if request.method == "POST":
        name = request.POST.get("name")
        objective = Work.objects.create(name=name)
        objective.save()
        students = Student.objects.all()
        for s in students:
            progress = Progress.objects.create(student_id=s.pk, work_id=objective.pk)
            progress.save()
    return render(request, 'study/index.html', context=context)
    #return HttpResponse(f'<h2>Запись {name} создана<h2>')


def create_obj(request):
    return render(request, 'study/create_objective.html')


def about(request):
    return render(request, 'study/about.html')  # Адрес папки с проектом, если мы поместили ее именно в templates


def page_not_found(request, exception):
    return HttpResponseNotFound('<h2>Страница не найдена</h2>')

mysite/study/templates/study/about.html
{% extends 'study/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Кандидат</p>
{% endblock %}

mysite/study/templates/study/base.html
<!DOCTYPE html>
{% load static %} <!-- Для подключения папки static -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <!--Получается название статической папки 'путь к файлу от static' -->
    <link type="text/css" href="{%static 'study/css/styles.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{%static 'study/images/ico.ico' %}" type="image/x-icon"/>
</head>
<body>
<!--<h1><a href="{%url 'study:index' %}">На главную</a></h1>-->
<p>
    <a href = "{%url 'study:index' %}">
        <img src="{%static 'study/images/N7.png'%}" width = 60 height = auto>
    </a>
</p>

{%block content%}

{% endblock %}

{% block mainmenu %}
<table class="for_buttons">
    {% for m in menu %}
    <!--<p><a href="{% url m.url_name%}">{{m.title}}</a></p>-->

    <tr>
        <td>
            <form action="{% url m.url_name%}">
          <button class="button_menu" type="submit"><b>{{m.title}}</b></button>
        </form>
        </td>

    </tr>

    {% endfor %}
</table>
{% endblock mainmenu %}

<tr><td valign="top">
    <div id="footer">
        <p>© 2021 Полное или частичное копирование и дальнейшее распространение всех материалов сайта не запрещено
            и даже приветствуется</p>
    </div>
</td></tr>
</body>
</html>

mysite/study/templates/study/create_objective.html
<!DOCTYPE html>
{% load static %} <!-- Для подключения папки static -->
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавить задание</title>
    <link type="text/css" href="{%static 'study/css/styles.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{%static 'study/images/ico.ico' %}" type="image/x-icon"/>
</head>
<body>
<form action="{% url 'study:new_obj'%}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Добавить новое задание</legend>
        <p><label>Название задания: </label><input class="base-input" type="text" name="name"></p>
        <p><label>Дата: </label><input class="base-input" type="date" name="date" ></p>
        <p><button class="button_main" type="submit"><b>Отправить</b></button></p>
    </fieldset>
</form>
</body>
</html>

<input type="date" id="start" name="trip-start"
       value="2018-07-22"
       min="2018-01-01" max="2018-12-31">

mysite/study/templates/study/group_list.html
{% extends 'study/base.html' %}
{% block content %}
<h1>{{title}}</h1>
<ul>
{% for s in students %}
    <li>
        <p>{{s.surname}} {{s.name}} {{s.group}}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

mysite/study/templates/study/groups.html
{% extends 'study/base.html' %}
{% block content %}
<h1>{{title}}</h1>
<ul>
{% for g in groups %}
    <li>
        <a href="{% url 'study:study_progress' g.pk%}"><p>Группа {{g.number}}. Год обучения {{g.study_year}}</p></a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

mysite/study/templates/study/index.html
{% extends 'study/base.html' %}
{% load static %}
{% block content %}
<img src="{%static 'study/images/Tali1.jpg' %}" width = 200 height = auto>
{% endblock %}

mysite/study/templates/study/progress.html
{% extends 'study/base.html' %}
{% block content %}
<!--<h1>{{title}}</h1>-->
<!--<h2><a href="{%url 'study:groups' %}">К списку групп</a></h2>-->
<form class="forBtn" action="{% url 'study:groups'%}">
          <button class="button_main" type="submit"><b>К списку групп</b></button>
</form>
<table>
     <tr>
       <th></th>
{% for h in headers %}
         <th>{{h}}</th>
{% endfor %}
     </tr>
{% for p in progress %}
    <tr>
        <th>{{p.surname}}</th>
        {% for w in p.table %}
            {% if w.status == 'Правки' %}
                    <td bgcolor="Red">{{w.status}}</td>
            {% elif w.status == 'Проверка' %}
                <td bgcolor="Yellow">{{w.status}}</td>
            {% elif w.status == 'Сдано' %}
                   <td bgcolor="Green">{{w.status}}</td>
            {%else%}
            <td >{{w.status}}</td>
            {%endif%}
        {% endfor %}
    </tr>
{% endfor %}
</table>

{% endblock %}